/**
 * createPR.mjs
 * Applies code patches, commits all changes to a new branch, and opens a PR.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { execSync } from 'child_process'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { updateSnapshot } from './diffSnapshots.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(__dirname, '..')

function exec(cmd, opts = {}) {
  return execSync(cmd, { cwd: REPO_ROOT, stdio: 'pipe', encoding: 'utf8', ...opts }).trim()
}

/**
 * Apply a single patch using literal string replacement.
 * Throws if currentCode is not found in the file (never silently corrupts).
 */
function applyPatch(change) {
  const filePath = join(REPO_ROOT, change.file)
  if (!existsSync(filePath)) {
    throw new Error(`File not found: ${change.file}`)
  }
  const content = readFileSync(filePath, 'utf8')
  if (!content.includes(change.currentCode)) {
    throw new Error(
      `Cannot apply patch to ${change.file} — currentCode not found in file.\n` +
      `Expected:\n${change.currentCode}\n\nThis may mean GPT-4o hallucinated the current code. Skip this change and review manually.`
    )
  }
  writeFileSync(filePath, content.replace(change.currentCode, change.proposedCode), 'utf8')
  console.log(`  Patched: ${change.file}`)
}

/**
 * Build a PR body from all changed sources and their proposals.
 */
function buildPRBody(changedSources) {
  const sections = changedSources.map(({ source, diff, proposal }) => {
    const confidenceBadge = { high: '🟢 High', medium: '🟡 Medium', low: '🔴 Low' }[proposal.confidence] ?? proposal.confidence

    const changeBlocks = proposal.changes.map(c => `
<details>
<summary><code>${c.file}</code></summary>

**Rationale:** ${c.rationale}

\`\`\`diff
- ${c.currentCode.split('\n').join('\n- ')}
+ ${c.proposedCode.split('\n').join('\n+ ')}
\`\`\`
</details>`).join('\n')

    return `## ${source.id} — [${source.description}](${source.url})

**Change type:** ${diff.type === 'new' ? 'Initial gap analysis (first-time monitoring)' : 'Doc content changed'}
**AI Confidence:** ${confidenceBadge}

**Summary:** ${proposal.summary}

${changeBlocks || '_No code changes proposed._'}`
  })

  return `# Automated Documentation Sync

This PR was opened automatically by the monthly docs-sync workflow.
It compares the current [DrDoctor HL7 spec docs](https://docs.dr.doctor) against the validator's rule files and proposes updates.

> ⚠️ **Always review before merging.** AI-generated patches should be verified against the live docs.

---

${sections.join('\n\n---\n\n')}

---

## Review checklist
- [ ] Verify proposed code changes against the live doc pages (links above)
- [ ] Run \`npm run build\` locally to confirm no TypeScript errors
- [ ] Check that any new/removed codes are intentional spec changes, not doc typos
- [ ] Merge when satisfied

---
*Generated by [docs-sync workflow](/.github/workflows/sync-docs.yml)*`
}

/**
 * Main entry point: create a branch, apply all patches, commit, push, open PR.
 *
 * @param {Array<{ source, diff, proposal }>} changedSources
 * @param {string} ghToken - GH_TOKEN for creating the PR via GitHub API
 */
export async function createPR(changedSources, ghToken) {
  const date = new Date().toISOString().slice(0, 10)
  const shortHash = Math.random().toString(36).slice(2, 8)
  const branch = `docs-sync/${date}-${shortHash}`

  // Create branch
  exec(`git checkout -b ${branch}`)
  console.log(`Created branch: ${branch}`)

  const failedPatches = []

  // Apply patches and update snapshots
  for (const { source, diff, proposal } of changedSources) {
    console.log(`\nApplying patches for: ${source.id}`)

    for (const change of proposal.changes) {
      try {
        applyPatch(change)
      } catch (err) {
        console.warn(`  WARNING: ${err.message}`)
        failedPatches.push({ source: source.id, file: change.file, reason: err.message })
      }
    }

    // Always update the snapshot (even if patches failed — we don't want to re-run on the same diff)
    updateSnapshot(source, diff.current)
    console.log(`  Snapshot updated: ${source.id}`)
  }

  // Stage changed files
  exec('git add src/constants/referenceData.ts || true')
  exec('git add src/validation/rules/ || true')
  exec('git add src/validation/messageTypeRules.ts || true')
  exec('git add data/snapshots/ || true')

  // Check if there's anything to commit
  const status = exec('git status --porcelain')
  if (!status) {
    console.log('No file changes after applying patches — skipping PR creation.')
    exec('git checkout master')
    exec(`git branch -D ${branch}`)
    return
  }

  const summaries = changedSources.map(({ source }) => source.id).join(', ')
  const commitMsg = `docs-sync: update rules from spec docs (${date})\n\nSources changed: ${summaries}\n\nCo-Authored-By: docs-sync-bot <docs-sync-bot@users.noreply.github.com>`

  exec(`git commit -m "${commitMsg.replace(/"/g, '\\"')}"`)
  exec(`git push origin ${branch}`)
  console.log(`\nPushed branch: ${branch}`)

  // Create PR via GitHub API
  const repo = exec('git remote get-url origin')
    .replace('https://github.com/', '')
    .replace(/\.git$/, '')
    .trim()

  const prTitle = `docs-sync: validator rules update (${date})`
  let prBody = buildPRBody(changedSources)

  if (failedPatches.length > 0) {
    prBody += `\n\n---\n\n## ⚠️ Patches that could not be applied automatically\n\nThese require manual review:\n` +
      failedPatches.map(f => `- **${f.source}** → \`${f.file}\`: ${f.reason}`).join('\n')
  }

  const prRes = await fetch(`https://api.github.com/repos/${repo}/pulls`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${ghToken}`,
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify({
      title: prTitle,
      body: prBody,
      head: branch,
      base: 'master',
    }),
  })

  if (!prRes.ok) {
    const err = await prRes.text()
    throw new Error(`Failed to create PR: ${prRes.status} ${err}`)
  }

  const pr = await prRes.json()
  console.log(`\nPR created: ${pr.html_url}`)
}
